DjangoWebProject/college/comp/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib import admin
from django.conf.urls import url, include
from django.views.generic import TemplateView

from .views import (
    RegisterView,
    CompanyCreateView,
    companyIndexView,
    postcompanyIndexView,
    UpdateCompany,
    deletecompany,
    rejectcompany,
    RemeetUpdateCompany,
    sendremeet,
    remeetcompanyIndexView,
    report,
    listuser,
    deleteuser,
    filterreport,
    UpdateUser
)

urlpatterns = [
    url(r'^$', LoginView.as_view(template_name='comp/registration/login.html'), name='login'),
    url(r'^register/$', RegisterView.as_view(), name='register'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^userlist/$', listuser, name='userview'),
    url(r'company/(?P<pk>[0-9]+)/$', deleteuser, name='deleteuser'),
    url(r'company/update/(?P<pk>[0-9]+)/$', UpdateUser.as_view(), name='updateuser'),

    url(r'^home/$', companyIndexView, name='home'),
    url(r'^post/$', postcompanyIndexView, name='postmeetingcompany'),
    url(r'^remeet/$', remeetcompanyIndexView, name='remeetcompanyindex'),
    url(r'^sendremeeting/(?P<pk>[0-9]+)$', sendremeet, name='addremeeting'),

    url(r'^company/create$', CompanyCreateView.as_view(), name="companycreate"),
    url(r'^com/(?P<pk>[0-9]+)/update$', UpdateCompany.as_view(), name="companyupdate"),
    url(r'^com/(?P<pk>[0-9]+)/delete$', deletecompany, name="companydelete"),
    url(r'^com/(?P<pk>[0-9]+)/deletereemeet$', rejectcompany, name="companyreject"),

    url(r'^com/(?P<pk>[0-9]+)/remeet$', RemeetUpdateCompany.as_view(), name="remeet"),
    url(r'^com/report$', report, name="report"),
    url(r'^com/filterreport$', filterreport, name='filterreport')
]

DjangoWebProject/college/company/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include

urlpatterns = [
    url(r'^', include('comp.urls')),
    url('admin/', admin.site.urls),
]

DjangoWebProject/college/comp/models.py
from django.db import models
from django.conf import settings

User = settings.AUTH_USER_MODEL

drop = (
    ('choose', 'CHOOSE'),
    ('product', 'PRODUCT'),
    ('service', 'SERVICE'),
)


class Company(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    company_name = models.CharField(max_length=150)
    company_type = models.CharField(max_length=150, choices=drop, default='choose')
    company_date = models.DateField()
    company_time = models.TimeField()
    door_no = models.CharField(max_length=150)
    street1 = models.CharField(max_length=150)
    street2 = models.CharField(max_length=150)
    city = models.CharField(max_length=150)
    state = models.CharField(max_length=150)
    pin_code = models.IntegerField()
    name = models.CharField(max_length=150)
    designation = models.CharField(max_length=150)
    ph_number = models.IntegerField()
    mailid = models.EmailField()
    job_description = models.TextField()
    company_requirements = models.TextField()
    remeet = models.BooleanField(default=False)
    timestamp = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.company_name

DjangoWebProject/college/comp/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.models import User
from django.contrib.auth import get_user_model
from django.views.generic import DetailView, CreateView, UpdateView
from django.http import Http404
from django.urls import reverse_lazy

from .models import Company

from .form import RegisterForm, CompanyCreateForm


class RegisterView(LoginRequiredMixin, CreateView):
    form_class = RegisterForm
    template_name = 'comp/registration/register.html'
    success_url = '/userlist/'

    def dispatch(self, *args, **kwargs):
        if self.request.user.is_superuser:
            return super(RegisterView, self).dispatch(*args, **kwargs)
        else:
            if self.request.user.is_authenticated:
                return redirect("/home/")
            return super(RegisterView, self).dispatch(*args, **kwargs)


def listuser(request):
    if request.user.is_superuser:
        users = User.objects.all()
        context = {'all': users}
        return render(request, 'comp/userview.html', context)
    else:
        return redirect("/home/")


def deleteuser(request, pk):
    wat = User.objects.filter(id=pk)
    wat.delete()
    users = User.objects.all()
    context = {'all': users}
    return render(request, 'comp/userview.html', context)


class UpdateUser(UpdateView):
    form_class = RegisterForm
    template_name = 'comp/updateuser.html'
    success_url = "/userlist/"

    def get_queryset(self, *args, **kwargs):
        return User.objects.filter(id=self.kwargs['pk'])


class UpdateCompany(UpdateView):
    model = Company
    fields = [
        'company_name',
        'company_type',
        'company_date',
        'company_time',
        'door_no',
        'street1',
        'street2',
        'city',
        'state',
        'pin_code',
        'name',
        'designation',
        'ph_number',
        'mailid',
        'job_description',
        'company_requirements']
    template_name = 'comp/CompanyUpdateForm.html'
    success_url = '/home'


class RemeetUpdateCompany(UpdateView):
    model = Company
    fields = [
        'company_date',
        'company_time',
        'company_requirements'
    ]
    template_name = 'comp/CompanyRemeetUpdate.html'
    success_url = '/home'

    def form_valid(self, form):
        instance = form.save(commit=False)
        instance.remeet = False
        # instance.save()
        return super(RemeetUpdateCompany, self).form_valid(form)

    def get_context_data(self, *args, **kwargs):
        context = super(RemeetUpdateCompany, self).get_context_data(*args, **kwargs)
        context['title'] = 'ADD Student'
        return context


class CompanyCreateView(LoginRequiredMixin, CreateView):
    form_class = CompanyCreateForm
    template_name = 'comp/CompanyForm.html'
    success_url = '/home'

    # login_url = '/userlogin/'

    def form_valid(self, form):
        instance = form.save(commit=False)
        instance.owner = self.request.user
        # instance.save()
        return super(CompanyCreateView, self).form_valid(form)

    def get_context_data(self, *args, **kwargs):
        context = super(CompanyCreateView, self).get_context_data(*args, **kwargs)
        context['title'] = 'ADD Student'
        return context


def deletecompany(request, pk):
    com = Company.objects.filter(id=pk)
    com.delete()
    return redirect('/home')


def rejectcompany(request, pk):
    com = Company.objects.filter(id=pk)
    com.delete()
    return redirect('/post')


def companyIndexView(request):
    if request.user.is_authenticated:
        import datetime
        todaydate = datetime.datetime.now().date()
        queryset = Company.objects.filter(owner=request.user).filter(company_date__gte=todaydate)
        context = {
            'objects': queryset
        }
        return render(request, 'comp/index.html', context)
    else:
        return redirect("/")


def postcompanyIndexView(request):
    if request.user.is_authenticated:
        import datetime
        todaydate = datetime.datetime.now().date()
        queryset = Company.objects.filter(owner=request.user).filter(company_date__lt=todaydate).filter(remeet=False)
        context = {
            'objects': queryset
        }
        return render(request, 'comp/postmeetingindex.html', context)
    else:
        return redirect("/")


def remeetcompanyIndexView(request):
    if request.user.is_authenticated:
        import datetime
        todaydate = datetime.datetime.now().date()
        queryset = Company.objects.filter(owner=request.user).filter(company_date__lt=todaydate).filter(remeet=True)
        context = {
            'objects': queryset
        }
        return render(request, 'comp/remeetingindex.html', context)
    else:
        return redirect("/")


def sendremeet(request, pk):
    obj = Company.objects.filter(id=pk)
    for i in obj:
        i.remeet = True
        i.save()
    return redirect('/home/')


def report(request):
    import datetime
    today = datetime.date.today()
    start_week = today - datetime.timedelta(today.weekday())
    end_week = start_week + datetime.timedelta(7)
    todaydate = datetime.datetime.now().date()
    thismonth = todaydate.month
    thisyear = todaydate.year
    thistime = datetime.datetime.now()
    if request.user.is_superuser:
        dayactive = Company.objects.filter(company_date=todaydate).filter(
            company_time__gte=thistime.time())
        daynactive = Company.objects.filter(company_date=todaydate).filter(
            company_time__lt=thistime.time())
        weekactive = Company.objects.filter(
            company_date__range=[start_week, end_week]).filter(
            company_date__gt=todaydate)
        weeknactive = Company.objects.filter(
            company_date__range=[start_week, end_week]).filter(
            company_date__lt=todaydate)
        monthactive = Company.objects.filter(company_date__year=thisyear).filter(
            company_date__month=thismonth).filter(
            company_date__gt=todaydate)
        monthnactive = Company.objects.filter(company_date__year=thisyear).filter(
            company_date__month=thismonth).filter(
            company_date__lt=todaydate)
        yearactive = Company.objects.filter(company_date__year=thisyear).filter(
            company_date__gt=todaydate)
        yearnactive = Company.objects.filter(company_date__year=thisyear).filter(
            company_date__lt=todaydate)
    else:
        dayactive = Company.objects.filter(owner=request.user).filter(company_date=todaydate).filter(
            company_time__gte=thistime.time())
        daynactive = Company.objects.filter(owner=request.user).filter(company_date=todaydate).filter(
            company_time__lt=thistime.time())
        weekactive = Company.objects.filter(owner=request.user).filter(
            company_date__range=[start_week, end_week]).filter(
            company_date__gt=todaydate)
        weeknactive = Company.objects.filter(owner=request.user).filter(
            company_date__range=[start_week, end_week]).filter(
            company_date__lt=todaydate)
        monthactive = Company.objects.filter(owner=request.user).filter(company_date__year=thisyear).filter(
            company_date__month=thismonth).filter(
            company_date__gt=todaydate)
        monthnactive = Company.objects.filter(owner=request.user).filter(company_date__year=thisyear).filter(
            company_date__month=thismonth).filter(
            company_date__lt=todaydate)
        yearactive = Company.objects.filter(owner=request.user).filter(company_date__year=thisyear).filter(
            company_date__gt=todaydate)
        yearnactive = Company.objects.filter(owner=request.user).filter(company_date__year=thisyear).filter(
            company_date__lt=todaydate)
    context = {
        'objectsdayactive': dayactive,
        'objectsdaynactive': daynactive,
        'objectsweekactive': weekactive,
        'objectsweeknactive': weeknactive,
        'objectsmonthactive': monthactive,
        'objectsmonthnactive': monthnactive,
        'objectsyearactive': yearactive,
        'objectsyearnactive': yearnactive
    }
    return render(request, 'comp/Report.html', context)


def filterreport(request):
    if request.method == 'POST':
        import datetime
        fildate = datetime.datetime.strptime(request.POST['date'], "%Y-%m-%d").date()
        print(fildate)
        today = datetime.datetime.now().date()
        start_week = fildate - datetime.timedelta(fildate.weekday())
        end_week = start_week + datetime.timedelta(7)
        todaydate = fildate
        thismonth = todaydate.month
        thisyear = todaydate.year
        thistime = datetime.datetime.now()
        if request.user.is_superuser:
            dayactive = Company.objects.filter(company_date=fildate).filter(company_date__gte=today)
            daynactive = Company.objects.filter(company_date=fildate).filter(company_date__lt=today)
            weekactive = Company.objects.filter(
                company_date__range=[start_week, end_week]).filter(
                company_date__gte=today)
            weeknactive = Company.objects.filter(
                company_date__range=[start_week, end_week]).filter(
                company_date__lt=today)
            monthactive = Company.objects.filter(company_date__year=thisyear).filter(
                company_date__month=thismonth).filter(
                company_date__gte=today)
            monthnactive = Company.objects.filter(company_date__year=thisyear).filter(
                company_date__month=thismonth).filter(
                company_date__lt=today)
            yearactive = Company.objects.filter(company_date__year=thisyear).filter(
                company_date__gte=today)
            yearnactive = Company.objects.filter(company_date__year=thisyear).filter(
                company_date__lt=today)
        else:

DjangoWebProject/college/comp/templates/comp/CompanyForm.html
{% extends 'comp/base.html' %}
{% block nav %}
    <div class="form">
        <form action="{% url 'companycreate' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="col-lg-4 col-md-4 col-sm-0 col-xs-0"></div>
            <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12 addCompany">
                {% include 'comp/form-template.html' %}
                <div class="btn btn-info col-lg-4 col-md-4 col-sm-4 col-xs-4 btn-sm companyReset">Reset</div>
                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4"></div>
                <button type="submit" class="btn btn-info col-lg-4 col-md-4 col-sm-4 col-xs-4 btn-sm companySubmit">
                    Submit
                </button>
            </div>

            <div class="col-lg-4 col-md-4 col-sm-0 col-xs-0">
            </div>
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <br>
            </div>
        </form>
    </div>
    <script>
        $('#id_company_name,#id_company_type,#id_company_date,#id_company_time,#id_door_no,#id_street1').addClass('form-control');
        $('#id_street2,#id_city,#id_state,#id_pin_code,#id_name,#id_designation,#id_ph_number,#id_mailid,#id_job_description,#id_company_requirements').addClass('form-control');
        $('#id_company_date').attr('type', 'date');
        $('#id_company_time').attr('type', 'time');
        $('#addcompany').css('background', 'black')
        $('#addcompany a').css('color', 'white')
    </script>
{% endblock %}

DjangoWebProject/college/comp/templates/comp/CompanyRemeetUpdate.html
{% extends 'comp/base.html' %}
{% block nav %}
    <div>
        <form method="post" action="" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="col-lg-4 col-md-4 col-sm-0 col-xs-0"></div>
            <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12 addCompany">
                <div class="form-group">
                    <label class="col-lg-6 col-md-6 col-sm-6 col-xs-6">New Date : </label>
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">{{ form.company_date }}</div>
                    <label class="col-lg-6 col-md-6 col-sm-6 col-xs-6">New Time : </label>
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">{{ form.company_time }}</div>
                    <label class="col-lg-6 col-md-6 col-sm-6 col-xs-6">New Requirements : </label>
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">{{ form.company_requirements }}</div>
                </div>
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12"><br></div>
                <div class="col-lg-2 col-md-2 col-sm-2 col-xs-2"></div>
                <button type="submit" class="btn btn-primary col-lg-8 col-md-8 col-sm-8 col-xs-8 btn-sm companySubmit">
                    Make Appointments
                </button>
                <div class="col-lg-2 col-md-2 col-sm-2 col-xs-2"></div>
            </div>

            <div class="col-lg-4 col-md-4 col-sm-0 col-xs-0">
            </div>
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <br>
            </div>
        </form>
    </div>
    <script>
        $('#id_company_name,#id_company_type,#id_company_date,#id_company_time,#id_door_no,#id_street1').addClass('form-control');
        $('#id_street2,#id_city,#id_state,#id_pin_code,#id_name,#id_designation,#id_ph_number,#id_mailid,#id_job_description,#id_company_requirements').addClass('form-control');
        $('#id_company_date').attr('type', 'date');
        $('#id_company_time').attr('type', 'time');
    </script>
{% endblock %}

DjangoWebProject/college/comp/templates/comp/CompanyUpdateForm.html
{% extends 'comp/base.html' %}
{% block nav %}
    <div>
        <form method="post" action="" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="col-lg-4 col-md-4 col-sm-0 col-xs-0"></div>
            <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12 addCompany">
                {% include 'comp/form-template.html' %}
                <div class="btn btn-info col-lg-4 col-md-4 col-sm-4 col-xs-4 btn-sm companyReset">Reset</div>
                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4"></div>
                <button type="submit" class="btn btn-info col-lg-4 col-md-4 col-sm-4 col-xs-4 btn-sm companySubmit">
                    Submit
                </button>
            </div>

            <div class="col-lg-4 col-md-4 col-sm-0 col-xs-0">
            </div>
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <br>
            </div>
        </form>
    </div>
    <script>
        $('#id_company_name,#id_company_type,#id_company_date,#id_company_time,#id_door_no,#id_street1').addClass('form-control');
        $('#id_street2,#id_city,#id_state,#id_pin_code,#id_name,#id_designation,#id_ph_number,#id_mailid,#id_job_description,#id_company_requirements').addClass('form-control');
        $('#id_company_date').attr('type', 'date');
        $('#id_company_time').attr('type', 'time');
    </script>
{% endblock %}

DjangoWebProject/college/comp/templates/comp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <!--external css-->
    <style>
        @media only screen and (max-width: 600px) {
            * {
                font-size: 12px;
            }

            h1,
            h2,
            div,
            legend,
            label {
                font-size: 12px;
            }
        }

        @media only screen and (max-width: 400px) {
            label {
                font-size: 85%;
            }
        }

        td {
            background-color: #d2dae2;
        }

        p {
            border: 2px solid black;
        }

        label {
            font-family: "Comic Sans MS", sans-serif;
            text-shadow: 3px 2px 2px #B4B2B2, 4px 3px 3px grey;
        }

        .userNameContent input[type=text],
        .passwordContent input[type=password] {
            border-radius: 5px;
            padding-left: 50px;
        }

        input[type=text]:focus,
        input[type=password]:focus,
        input[type=number]:focus,
        input[type=email]:focus,
        input[type=date]:focus,
        input[type=time]:focus {
            border: 1px solid hsl(0, 16%, 84%);
            border-radius: 20px;
        }
        .pendingIcon a {
            background-color: whitesmoke;
        }

        .report a {
            border-radius: 30%;
            border: 2px solid black;
            background-color: whitesmoke;
        }
        .pendingIcon b,
        .report b,
        .userSetting b {
            color: red;
        }

        .add a {
            border-radius: 50%;
            border: 2px solid black;
            background-color: whitesmoke;
        }

        .pendingDrop li {
            cursor: pointer;
        }

        td,
        th {
            border: 1px solid black;
            border-color: black;
            text-align: center;
            font-weight: bold;
            color: black;
            padding: 10px;
        }
    </style>
    <!--bootstrap  link-->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
          crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css"
          integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp"
          crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
            integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
            crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <!--jquery link-->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <!--<script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-1.7.min.js"></script>-->
    <script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.2.1.min.js"></script>

    <!--external Script-->
    <script>
        $(document).ready(function () {
            $('body').css('background-color', 'hsl(0, 16%, 84%)');
            $('.panel').css('border-radius', '5%');
            $('.panel').hover(function () {
                $(this).css({
                    'cursor': 'pointer',
                    'box-shadow': '3px 4px 5px grey'
                })
            })

            $('.panel').mouseleave(function () {
                $(this).css({
                    'box-shadow': 'none'
                })
            })

        })
    </script>
</head>
<body>
<nav class="navbar navbar-inverse" style="border-radius:0%;">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="{% url "home" %}" class="navbar-brand"><b>CA</b></a>
        </div>
        <div class="collapse navbar-collapse" id="myNavbar">
            <ul class="nav navbar-nav" >
                <li id="home"><a  id="logo" href="{% url "home" %}"> <span class="glyphicon glyphicon-home"></span> <b>Home</b></a></li>
                {% if user.is_superuser %}
                    <li id="createuser">
                        <a href="{% url 'register' %}">
                            <span class="glyphicon glyphicon-user"></span>
                            <span class="glyphicon glyphicon-plus"></span>
                            <b>Createuser</b>
                        </a>
                    </li>
                    <li id="viewuser">
                        <a href="{% url 'userview' %}">
                            <span class="glyphicon glyphicon-user"></span>
                            <b>Viewuser</b>
                        </a>
                    </li>
                {% endif %}
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li id="addcompany">
                    <a href="{% url "companycreate" %}"><span
                            class="glyphicon glyphicon-plus"></span>
                        <b>Add company</b>
                    </a>
                </li>
                <li id="pending">
                    <a class="dropdown-toggle" data-toggle="dropdown">
                        <b> Pending</b>
                    </a>
                    <ul class="dropdown-menu ">
                        <li><a href="{% url 'postmeetingcompany' %}">Post-meeting</a>
                        </li>
                        <li class="divider"></li>
                        <li><a href="{% url 'remeetcompanyindex' %}">Re-meeting</a></li>
                    </ul>
                </li>
                <li id="report">
                    <a href="{% url 'report' %}">
                        <b>Report</b>
                    </a>
                </li>
                <li>
                    <a class="dropdown-toggle user" data-toggle="dropdown">
                        <b>hello,{{ request.user.username }}</b>
                    </a>
                    <ul class="dropdown-menu dropdown-menu-right">
                        <li><a>{{ request.user.username }}</a></li>
                        <li class="divider"></li>
                        <li><a>Dept</a></li>
                        <li class="divider"></li>
                        <li><a href="{% url 'logout' %}">Log out</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>

{% block nav %}
{% endblock %}
</body>
</html>

DjangoWebProject/college/comp/templates/comp/form-template.html
{% for field in form %}
    <div class="form-group">
        <label for="{{ field.label }}" class="col-lg-6 col-md-6 col-sm-6 col-xs-6">{{ field.label }}</label>
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">{{ field }}</div>
    </div>
{% endfor %}

DjangoWebProject/college/comp/templates/comp/link.html
{% load staticfiles %}
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<title>Document</title>
<!--bootstrap  link-->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
      integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
      crossorigin="anonymous">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css"
      integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp"
      crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
        integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
        crossorigin="anonymous"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<!--jquery link-->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!--<script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-1.7.min.js"></script>-->
<script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.2.1.min.js"></script>
<script src="jquery-3.2.1.min.js"></script>

<!--external Script-->


{% block link %}
{% endblock %}

DjangoWebProject/college/comp/templates/comp/userview.html
{% extends 'comp/base.html' %}

{% block nav %}

    <div class="container">
        {% for obj in all %}
            <div class="row">
                <span class="well well-sm col-lg-3 col-md-3 col-sm-3 col-xs-3">{{ obj.username }}</span>
                <span class="well well-sm col-lg-3 col-md-3 col-sm-3 col-xs-3">{{ obj.email }}</span>
                <form action="{% url 'updateuser' obj.id %}" class="col-lg-3 col-md-3 col-sm-3 col-xs-3">
                    {% csrf_token %}
                    <button class="btn btn-success col-lg-12 col-md-12 col-sm-12 col-xs-12">Edit</button>
                </form>
                <form action="{% url 'deleteuser' obj.id %}" class="col-lg-3 col-md-3 col-sm-3 col-xs-3">
                    {% csrf_token %}
                    <button class="btn btn-danger col-lg-12 col-md-12 col-sm-12 col-xs-12">Delete</button>
                </form>
            </div>
        {% endfor %}
    </div>
    <script>
        $(document).ready(function () {
            $('#viewuser').css('background', 'black')
            $('#viewuser a').css('color', 'white')
        })
    </script>

{% endblock %}