DjangoWebProject/company/app/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.conf.urls import url, include
from django.views.generic import TemplateView
from .views import *

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='app/first.html'), name='preload'),
    url(r'^test/$', TemplateView.as_view(template_name='app/test.html'), name='test'),
    url(r'^thankyou$', TemplateView.as_view(template_name='app/last.html'), name='thankyou'),
    url(r'home/$', index, name='index'),

    url(r'^login/$', LoginView.as_view(template_name='app/registration/login.html'), name='login'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^register/$', RegisterView.as_view(), name='register'),
    url(r'^userlist/$', listuser, name='userview'),
    url(r'user/(?P<pk>[0-9]+)/$', deleteuser, name='deleteuser'),
    url(r'user/update/(?P<pk>[0-9]+)/$', UpdateUser.as_view(), name='updateuser'),

    url(r'^upcome/$', collegeIndexView, name='upcoming'),
    url(r'^college/create$', CollegeCreateView.as_view(), name="collegecreate"),
    url(r'^college/(?P<pk>[0-9]+)/update$', UpdateCollege.as_view(), name="collegeupdate"),
    url(r'^college/(?P<pk>[0-9]+)/delete$', deletecollege, name="collegedelete"),

    url(r'^post/$', postrecruitmentIndexView, name='postrecruitment'),
    url(r'^rerecruit/$', rerecruitIndexView, name='rerecruitment'),
    url(r'^sendrerecruit/(?P<pk>[0-9]+)$', sendrerecruit, name='addrerecruit'),
    url(r'^college/(?P<pk>[0-9]+)/rerecruit$', RerecruitUpdateCollege.as_view(), name="rerecruit"),
    url(r'^college/(?P<pk>[0-9]+)/deletererecruit$', rejectcollege, name="collegereject"),

    url(r'^college/report$', report, name="report"),
    url(r'^college/filterreport$', filterreport, name='filterreport')

]

DjangoWebProject/company/company/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^', include('app.urls'))
]

DjangoWebProject/company/app/models.py
from django.db import models
from django.conf import settings

User = settings.AUTH_USER_MODEL

drop = (
    ('choose', 'CHOOSE'),
    ('autonomous', 'autonomous'),
    ('annauniversity', 'annauniversity'),
)


class College(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    college_name = models.CharField(max_length=150)
    college_type = models.CharField(max_length=150, choices=drop, default='choose')
    college_date = models.DateField()
    college_time = models.TimeField()
    address = models.CharField(max_length=1000)
    city = models.CharField(max_length=150)
    state = models.CharField(max_length=150)
    pin_code = models.IntegerField()
    placement_staff_name = models.CharField(max_length=150)
    ph_number = models.IntegerField()
    mailid = models.EmailField()
    ave_count = models.IntegerField()
    remeet = models.BooleanField(default=False)
    timestamp = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.college_name

DjangoWebProject/company/templates/app/CollegeRerecruitUpdate.html
{% extends 'app/base.html' %}
{% block link %}
    <div>
        <form method="post" action="" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="col-lg-4 col-md-4 col-sm-0 col-xs-0"></div>
            <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
                <div class="form-group">
                    <label class="col-lg-6 col-md-6 col-sm-6 col-xs-6">New-Date : </label>
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">{{ form.college_date }}</div>
                    <label class="col-lg-6 col-md-6 col-sm-6 col-xs-6">New-Time : </label>
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">{{ form.college_time }}</div>
                    <label class="col-lg-6 col-md-6 col-sm-6 col-xs-6">Avg-Count : </label>
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">{{ form.ave_count }}</div>
                </div>
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12"><br></div>
                <div class="col-lg-2 col-md-2 col-sm-2 col-xs-2"></div>
                <button type="submit" class="btn btn-primary col-lg-8 col-md-8 col-sm-8 col-xs-8 btn-sm collegeSubmit">
                    Make Recruitment
                </button>
                <div class="col-lg-2 col-md-2 col-sm-2 col-xs-2"></div>
            </div>

            <div class="col-lg-4 col-md-4 col-sm-0 col-xs-0">
            </div>
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <br>
            </div>
        </form>
    </div>
    <script>
        $('#id_college_date,#id_college_time,#id_ave_count').addClass('form-control');
        $('#id_college_date,#id_college_time,#id_ave_count').val("")
        $('#id_college_date').attr('type', 'date');
        $('#id_college_time').attr('type', 'time');
    </script>
{% endblock %}

DjangoWebProject/company/templates/app/CollegeUpdateForm.html
{% extends 'app/base.html' %}
{% block link %}
    <div>
        <form method="post" action="" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="col-lg-4 col-md-4 col-sm-0 col-xs-0"></div>
            <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12 addcollege">
                {% include 'app/form-template.html' %}
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12"><br></div>
                <div class="btn btn-danger col-lg-4 col-md-4 col-sm-4 col-xs-4 btn-sm collegeReset" onclick="reset()">Reset</div>
                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4"></div>
                <button type="submit" class="btn btn-success col-lg-4 col-md-4 col-sm-4 col-xs-4 btn-sm collegeSubmit">
                    Submit
                </button>
            </div>

            <div class="col-lg-4 col-md-4 col-sm-0 col-xs-0">
            </div>
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <br>
            </div>
        </form>
    </div>
    <script>
        $('#id_college_name,#id_college_type,#id_college_date,#id_college_time,#id_address').addClass('form-control');
        $('#id_city,#id_state,#id_pin_code,#id_placement_staff_name,#id_ph_number,#id_mailid,#id_ave_count').addClass('form-control');
        $('#id_college_date').attr('type', 'date');
        $('#id_college_time').attr('type', 'time');

        function reset() {
            $('#id_college_name,#id_college_type,#id_college_date,#id_college_time,#id_address,#id_city,#id_state,#id_pin_code,#id_placement_staff_name,#id_ph_number,#id_mailid,#id_ave_count').val("");
        }
    </script>
{% endblock %}

DjangoWebProject/company/templates/app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load staticfiles %}
    <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'bootstrap/css/bootstrap-theme.min.css' %}" rel="stylesheet">
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'jquery/j.min.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <link href="{% static 'bootstrap/css/bootstrap.css' %}" rel="stylesheet">
    <script src="{% static 'jquery/j.min.js' %}"></script>
    <script src="{% static 'jquery/j.min.js' %}"></script>
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <script src="{% static 'js/script.js' %}"></script>

    <link rel="icon" href="{% static 'images/icon.png' %}">
    <title>HR Assistant</title>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans+Condensed:300,700' rel='stylesheet' type='text/css'>
</head>
<body>

<nav class="navbar navbar-inverse" style="border-radius:0%;">
    <div class="container-fluid ">
        <div class="navbar-header">

            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="/home" class="navbar-brand"><b>HR Assistant</b></a>
        </div>
        <div class="collapse navbar-collapse" id="myNavbar">
            <ul class="nav navbar-nav">
                <li id="home"><a id="logo" href="{% url 'index' %}"><span class="glyphicon glyphicon-home"></span> <b>Home</b></a>
                </li>
                {% if user.is_superuser %}
                    <li id="createuser">
                        <a href="{% url 'register' %}">
                            <span class="glyphicon glyphicon-"></span>
                            <span class="glyphicon glyphicon-plus"></span>
                            <b>Createuser</b>
                        </a>
                    </li>
                    <li id="viewuser">
                        <a href="{% url 'userview' %}">
                            <span class="glyphicon glyphicon-user"></span>
                            <b>Viewuser</b>
                        </a>
                    </li>
                {% endif %}
                {% if user.is_authenticated %}
                    <li id="recruitment">
                        <a id="text" class="dropdown-toggle" data-toggle="dropdown">
                            <span class="glyphicon glyphicon-education"></span>
                            <b>Recruitments</b>
                        </a>
                        <ul class="dropdown-menu pendingDrop">
                            <li><a href="{% url 'upcoming' %}">Upcoming-recruitments</a></li>
                            <li class="divider"></li>
                            <li><a href="{% url 'postrecruitment' %}">Missed-recruitments</a></li>
                            <li class="divider"></li>
                            <li><a href="{% url 'rerecruitment' %}">Re-recruitments</a></li>
                        </ul>
                    </li>
                    <li id="addcollege">
                        <a href="{% url 'collegecreate' %}"><span class="glyphicon glyphicon-plus"></span><b>Add
                            college</b></a>
                    </li>
                    <li id="report">
                        <a class="report" href="{% url 'report' %}">
                            <span class="glyphicon glyphicon-send"></span>
                            <b>Report</b>
                        </a>
                    </li>
                {% endif %}
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                    <li class="log">
                        <a href="{% url 'login' %}">
                            <span class="glyphicon glyphicon-user"></span>
                            <b>Hello, {{ user.username }}</b>
                        </a>
                    </li>
                {% else %}
                    <li class="log">
                        <a href="{% url 'login' %}">
                            <span class="glyphicon glyphicon-log-in"></span>
                            <b>Login</b>
                        </a>
                    </li>
                {% endif %}

            </ul>
        </div>
    </div>
</nav>

{% block link %}
{% endblock %}
</body>
</html>

DjangoWebProject/company/templates/app/collegeform.html
{% extends 'app/base.html' %}
{% block link %}
    <div class="form">
        <form action="{% url 'collegecreate' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="col-lg-4 col-md-4 col-sm-0 col-xs-0"></div>
            <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12 addCollege">
                {% include 'app/form-template.html' %}
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12"><br></div>
                <div class="btn btn-danger col-lg-4 col-md-4 col-sm-4 col-xs-4 btn-sm collegeReset" onclick="reset()">
                    Reset
                </div>
                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4"></div>
                <button type="submit" class="btn btn-success col-lg-4 col-md-4 col-sm-4 col-xs-4 btn-sm collegeSubmit">
                    Submit
                </button>
            </div>

            <div class="col-lg-4 col-md-4 col-sm-0 col-xs-0">
            </div>
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <br>
            </div>
        </form>
    </div>
    <script>
        $('#id_college_name,#id_college_type,#id_college_date,#id_college_time,#id_address').addClass('form-control');
        $('#id_city,#id_state,#id_pin_code,#id_placement_staff_name,#id_ph_number,#id_mailid,#id_ave_count').addClass('form-control');
        $('#id_college_date').attr('type', 'date');
        $('#id_college_time').attr('type', 'time');

        function reset() {
            $('#id_college_name,#id_college_type,#id_college_date,#id_college_time,#id_address,#id_city,#id_state,#id_pin_code,#id_placement_staff_name,#id_ph_number,#id_mailid,#id_ave_count').val("");
        }
    </script>
    <style>
    #addcollege{
        background:black;
    }
    #addcollege a{
        color:white;
    }
    </style>
{% endblock %}

DjangoWebProject/company/templates/app/first.html
<meta http-equiv="refresh" content="4;url={% url 'index' %}"/>
<div class="loader tri"></div>
<div class="loader tri2"></div>
<div class="loader tri3"></div>
<div class="loader tri4"></div>
<div class="loader circ"></div>
<div class="loader circ2"></div>


<style>


    body {
        background: black;
    }

    .loader {
        border-radius: 50%;
        margin: 0 auto;
        position: absolute;
        top: 40%;
        left: 0;
        right: 0;
        height: 50px;
        width: 50px;
    }

    .tri {
        animation: translateRotation 1.5s infinite reverse;
        -webkit-animation: translateRotation 1.5s infinite reverse;
        border-left: 60px solid transparent;
        border-right: 60px solid transparent;
        border-top: 0 solid transparent;
        border-bottom: 60px solid #00b4ff;
        width: 0px;
        z-index: 2;
    }

    .tri2 {
        animation: translateRotation 1.5s infinite;
        -webkit-animation: translateRotation 1.5s infinite;
        border-left: 40px solid transparent;
        border-right: 40px solid transparent;
        border-top: 0px solid transparent;
        border-bottom: 40px solid #ffde15;
        width: 0px;
        z-index: 1;
    }

    .tri3 {
        animation: translateRotation 1.5s infinite;
        -webkit-animation: translateRotation 1.5s infinite;
        border-left: 40px solid transparent;
        border-right: 40px solid transparent;
        border-top: 40px solid #1da158;
        border-bottom: 0px solid transparent;
        width: 0px;
        z-index: 1;
    }

    .tri4 {
        animation: translateRotation 1.5s infinite reverse;
        -webkit-animation: translateRotation 1.5s infinite reverse;
        border-left: 60px solid transparent;
        border-right: 60px solid transparent;
        border-top: 60px solid #ea343f;
        border-bottom: 0px solid transparent;
        width: 0px;
        z-index: 2;
    }

    .circ {
        border: 30px solid rgba(255, 255, 255, 0.1);
    }

    .circ2 {
        border: 25px solid rgba(255, 255, 255, 1);
        box-sizing: border-box;
        box-shadow: 0 2px 1px rgba(0, 0, 0, 0.15), 0 -2px 1px rgba(0, 0, 0, 0.15), -2px 0 1px rgba(0, 0, 0, 0.15), 2px 0 1px rgba(0, 0, 0, 0.15);
        margin-top: 30px;
        z-index: 90;
    }


    @-webkit-keyframes translateRotation {
        0% {
            -webkit-transform: rotate(0deg);
        }
        100% {
            -webkit-transform: rotate(360deg);
        }
    }

    .plug {
        display: inline-block;
        position: absolute;
        bottom: 1rem;
        right: 1rem;

        color: #FFF;
        font-size: 1.2em;
        font-family: Sans-Serif;
        font-weight: bold;
    }


</style>

DjangoWebProject/company/templates/app/form-template.html
{% for field in form %}
    <div class="form-group">
        <label for="{{ field.label }}" class="col-lg-6 col-md-6 col-sm-6 col-xs-6">{{ field.label }}</label>
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">{{ field }}</div>
    </div>
{% endfor %}

DjangoWebProject/company/templates/app/home.html
{% extends 'app/base.html' %}
{% load staticfiles %}

{% block link %}
    <img src="{% static 'images/5.jpg' %}" width="100%">
    <br><br>
    <div class="container">
        <div class="row">
            <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                <h3>This is a product of ctOS a private company.</h3>
            </div>
            <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                <h3>This is a personal HR assistant for recruiters.</h3>
            </div>
        </div>
        <br>
        <div class="row">
            <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                <blockquote>
                    <p>For 50 years, WWF has been protecting the future of nature. The world's leading conservation
                        organization, WWF works in 100 countries and is supported by 1.2 million members in the United
                        States and close to 5 million globally.</p>
                    <footer>From WWF's website</footer>
                </blockquote>
            </div>
            <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                <blockquote>
                    <p>The ctOS corporate increased its share and still now holding the brand name for its Income and
                        management.</p>
                    <footer>BBC news</footer>
                </blockquote>
            </div>
        </div>
        <div class="row">
            <h1>Services</h1>
            <div class="col-lg-5 col-md-5 col-sm-12 col-xs-12 box">
                <center>
                    <img src="{% static 'images/b1.png' %}" height="40%" width="40%">
                </center>
                <br>
                <p>It has a user login interface where our company files are highly secured by using standard encoding
                    and decoding for our files.</p>
                <br>
            </div>

            <div class="col-lg-2 col-md-2 col-sm-12 col-xs-12"></div>

            <div class="col-lg-5 col-md-5 col-sm-12 col-xs-12 box1">
                <center>
                    <img src="{% static 'images/b2.png' %}" height="40%" width="40%">
                </center>
                <br>
                <p>HR assistant makes the documentation of the recruitment process so easy for our staff and keeps us
                    punctual</p>
                <br>
            </div>

        </div>
        <br><br>
        <div class="row">
            <div class="col-lg-5 col-md-5 col-sm-12 col-xs-12 box1">
                <center>
                    <img src="{% static 'images/b3.png' %}" height="40%" width="40%">
                </center>
                <br>
                <p>Highly secured database with standard hashing of every content including comma and dot.</p>
                <br>
            </div>

            <div class="col-lg-2 col-md-2 col-sm-12 col-xs-12"></div>

            <div class="col-lg-5 col-md-5 col-sm-12 col-xs-12 box">
                <center>
                    <img src="{% static 'images/b4.png' %}" height="40%" width="40%">
                </center>
                <br>
                <p>No laptap or battery drained ? don't worry, we have mobo respnsive webcontent. Its easy as you
                    like.</p>
                <br>
            </div>
        </div>
        <br><br>

    </div>
    <div class="container-fluid">
        <div class="row foot">
            <center>
                © Copyrights reserved-18.<br>
                Designed by Indeed Designers.
            </center>
        </div>
    </div>
    <style>
        .navbar {
            margin-bottom: 0px;
        }

        .box {
            background: #34495e;
            color: white;
            padding: 20px 20px 20px 20px;
        }

        .box1 {
            background: #7f8c8d;
            color: white;
            padding: 20px 20px 20px 20px;
        }

        .foot {
            background: #8395a7;
            padding: 30px 30px 30px 30px;
            color: white;
        }

        #home {
            background: black;
        }

        #home a {
            color: white;
        }
    </style>

{% endblock %}

DjangoWebProject/company/templates/app/postrecruitmentindex.html
{% extends 'app/base.html' %}
{% block link %}
    <div>
        <div class="UpcomingAppointments">
            {% if objects.count == 0 %}
                <h3 class="col-lg-12 col-md-12 col-sm-12 col-xs-12 text-responsive">
                    You Have No Missed Recruitment List
                </h3>
            {% else %}
                <h3 class="col-lg-12 col-md-12 col-sm-12 col-xs-12 text-responsive">
                    Missed Recruitments
                </h3>
            {% endif %}
            <div class="container-fluid">
                <div class="row getInto">
                    {% for college in objects %}
                        <div class="hide">
                            <div class='red{{ college.id }}'>
                                <hr>
                                <div class='col-lg-4 col-md-4 col-sm-0 col-xs-0'></div>
                                <div class='col-lg-4 col-md-4 col-sm-12 col-xs-12 up1'>
                                    <label class='col-lg-6 col-md-6 col-sm-6 col-xs-6'> college Name: </label>
                                    <label class='col-lg-6 col-md-6 col-sm-6 col-xs-6'>{{ college.college_name }}</label>
                                    <label class='col-lg-6 col-md-6 col-sm-6 col-xs-6'> Type of college: </label>
                                    <label class='col-lg-6 col-md-6 col-sm-6 col-xs-6'>{{ college.college_type }}</label>
                                    <label class='col-lg-6 col-md-6 col-sm-6 col-xs-6'> Date: </label>
                                    <label class='col-lg-6 col-md-6 col-sm-6 col-xs-6'>{{ college.college_date }}</label>
                                    <label class='col-lg-6 col-md-6 col-sm-6 col-xs-6'> Time: </label>
                                    <label class='col-lg-6 col-md-6 col-sm-6 col-xs-6'>{{ college.college_time }}</label>
                                    <div id='tcollegeLocation' class='container-fluid'>
                                        <div class='row'>
                                            <label class='col-lg-6 col-md-6 col-sm-6 col-xs-6'> Address</label>
                                            <label class='col-lg-6 col-md-6 col-sm-6 col-xs-6'>{{ college.address }}</label>
                                            <label class='col-lg-6 col-md-6 col-sm-6 col-xs-6'> City: </label>
                                            <label class='col-lg-6 col-md-6 col-sm-6 col-xs-6'>{{ college.city }}</label>
                                            <label class='col-lg-6 col-md-6 col-sm-6 col-xs-6'> State: </label>
                                            <label class='col-lg-6 col-md-6 col-sm-6 col-xs-6'>{{ college.state }}</label>
                                            <label class='col-lg-6 col-md-6 col-sm-6 col-xs-6'>Pincode: </label>
                                            <label class='col-lg-6 col-md-6 col-sm-6 col-xs-6'>{{ college.pin_code }}</label>
                                        </div>
                                    </div>
                                    <br>
                                    <div id='tcontactDetails' class='container-fluid'>
                                        <div class='row'>
                                            <div class='col-lg-12 col-md-12 col-sm-12 col-xs-12'>
                                                <fieldset id='tcollegeLocationField'
                                                          class='col-lg-12 col-md-12 col-sm-12 col-xs-12'>
                                                    <legend> Contact Details</legend>
                                                    <label class='col-lg-6 col-md-6 col-sm-6 col-xs-6'> Name: </label>
                                                    <label class='col-lg-6 col-md-6 col-sm-6 col-xs-6'>{{ college.placement_staff_name }}</label>
                                                    <label class='col-lg-6 col-md-6 col-sm-6 col-xs-6'> Ph
                                                        Number: </label>
                                                    <label class='col-lg-6 col-md-6 col-sm-6 col-xs-6'>{{ college.ph_number }}</label>
                                                    <label class='col-lg-6 col-md-6 col-sm-6 col-xs-6'> MailId: </label>
                                                    <label class='col-lg-6 col-md-6 col-sm-6 col-xs-6'>{{ college.mailid }}</label>
                                                    <label class='col-lg-6 col-md-6 col-sm-6 col-xs-6'>
                                                        Avg-count </label>
                                                    <label class='col-lg-6 col-md-6 col-sm-6 col-xs-6'>{{ college.ave_count }}</label>
                                                </fieldset>
                                                <div class='col-lg-1 col-md-1 col-sm-0 col-xs-0'></div>
                                            </div>
                                            <div class='col-lg-1 col-md-1 col-sm-0 col-xs-0'></div>
                                        </div>
                                    </div>
                                </div>
                                <div class='col-lg-4 col-md-4 col-sm-0 col-xs-0'></div>
                            </div>
                        </div>
                        <div class='col-lg-4 col-md-4 col-sm-6 col-xs-12 '>
                            <div class='panel col-lg-12 col-md-12 col-sm-12 col-xs-12 upcoming'>
                                <div class='panel-body col-lg-12 col-md-12 col-sm-12 col-xs-12'
                                     onclick="funa({{ college.id }})">
                                    <label class='col-lg-6 col-md-6 col-sm-6 col-xs-6'>College-name</label>
                                    <label class='col-lg-6 col-md-6 col-sm-6 col-xs-6'>{{ college.college_name }}</label>
                                    <label class='col-lg-6 col-md-6 col-sm-6 col-xs-6'>Date</label>
                                    <label class='col-lg-6 col-md-6 col-sm-6 col-xs-6'>{{ college.college_date }}</label>
                                    <label class='col-lg-6 col-md-6 col-sm-6 col-xs-6'>Time</label>
                                    <label class='col-lg-6 col-md-6 col-sm-6 col-xs-6'>{{ college.college_time }}</label>
                                    <label class='col-lg-6 col-md-6 col-sm-6 col-xs-6'>Contact person</label>
                                    <label class='col-lg-6 col-md-6 col-sm-6 col-xs-6'>{{ college.placement_staff_name }}</label>
                                    <label class='col-lg-6 col-md-6 col-sm-6 col-xs-6'>Contact number</label>
                                    <label class='col-lg-6 col-md-6 col-sm-6 col-xs-6'>{{ college.ph_number }}</label>
                                    <label class='col-lg-6 col-md-6 col-sm-6 col-xs-6'>Contact mail Id</label>
                                    <label class='col-lg-6 col-md-6 col-sm-6 col-xs-6'>{{ college.mailid }}</label>
                                </div>
                                <a href="/sendrerecruit/{{ college.id }}">
                                    <button type="submit"
                                            class='btn btn-success col-lg-4 col-md-4 col-sm-4 col-xs-4 btn-sm'>
                                        Accept
                                    </button>
                                </a>
                                <a href="/college/{{ college.id }}/deletererecruit">
                                    <button type="submit"
                                            class='btn btn-success col-lg-4 col-md-4 col-sm-4 col-xs-4 btn-sm'>
                                        Reject
                                    </button>
                                </a>
                                <a href="/college/{{ college.id }}/rerecruit">
                                    <button class='btn btn-success col-lg-4 col-md-4 col-sm-4 col-xs-4 btn-sm'>
                                        Re-recruit
                                    </button>
                                </a>
                                <br><br>
                            </div>
                        </div>
                        <script>
                            $(document).ready(function () {
                                $('.hide').hide();
                            })
                        </script>

                    {% endfor %}
                    <script>
                        function funa(let) {
                            $('.mainPage').hide();
                            $('.UpcomingAppointments').hide();
                            $('.onTouchComp').html($('.red' + let).html());
                            $('.onTouchComp').show();
                            $('.postMeetingForm').hide();
                            $('.reporting').hide();
                        }

                        $(document).ready(function () {
                            $('.onTouchComp').click(function () {
                                $(this).hide()
                                $('.UpcomingAppointments').show();
                            });
                        })
                    </script>
                    <style>
                        .upcoming {
                            background: #fdcb6e;
                            padding-bottom: 10px;
                            border-radius:0%;
                        }

                        .up1 {
                            background: #273c75;
                            color: white;
                            padding-bottom: 10px;
                            padding-top: 10px;
                        }

                        legend {
                            color: white;
                        }

                        #recruitment {
                            background: black;
                        }

                        #recruitment #text {
                            color: white;
                        }
                    </style>

                </div>
            </div>
        </div>
    </div>
    <div class="onTouchComp">
    </div>


    </body>
{% endblock %}